language: generic
sudo: required
services:
  - docker
script:
  - docker run -t -u $(id -u) -v $(pwd):/mnt -w /mnt crystallang/crystal bash -c "bash travis_rethinkdb.sh && crystal deps && crystal spec"