name: Crystal CI

on: [push]

jobs:
  spec:
    runs-on: ubuntu-latest

    services:
      rethinkdb:
        image: rethinkdb:2.4.0
        ports:
          - 28015:28015

    container:
      image: crystallang/crystal:0.33.0

    steps:
      - uses: actions/checkout@v1

      - name: Install LibDuktape and LibRocksDB
        run: |
          apt-get update && \
          apt install debian-archive-keyring && \
          ln -s /usr/share/keyrings/debian-archive*.gpg /etc/apt/trusted.gpg.d/ && \
          echo "deb http://httpredir.debian.org/debian/ buster main contrib non-free" >> /etc/apt/sources.list && \
          apt-get update && \
          apt-get install duktape-dev librocksdb-dev -y

      - name: Install dependencies from shards
        run: shards install

      - name: Run tests
        run: crystal spec

      - name: Run tests with -Dpreview_mt
        run: crystal spec -Dpreview_mt

  checks:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:0.33.0

    steps:
      - uses: actions/checkout@v1

      - name: Install LibDuktape and LibRocksDB
        run: |
          apt-get update && \
          apt install debian-archive-keyring && \
          ln -s /usr/share/keyrings/debian-archive*.gpg /etc/apt/trusted.gpg.d/ && \
          echo "deb http://httpredir.debian.org/debian/ buster main contrib non-free" >> /etc/apt/sources.list && \
          apt-get update && \
          apt-get install duktape-dev librocksdb-dev -y

      - name: Install dependencies from shards
        run: shards install

      - name: Build main.cr
        run: crystal build src/main.cr

      - name: Build main.cr with -Dpreview_mt
        run: crystal build -Dpreview_mt src/main.cr

      - name: Check format
        run: crystal tool format --check

      - name: Ensure every file requires everything it needs to build by itself
        run: for file in $(find src -name '*.cr'); do echo $file; crystal build --no-codegen $file --error-trace || exit 1; done;

      - name: Ensure every file requires everything it needs to build by itself with -Dpreview_mt
        run: for file in $(find src -name '*.cr'); do echo $file; crystal build --no-codegen -Dpreview_mt $file --error-trace || exit 1; done;
