name: Crystal CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      rethinkdb:
        image: rethinkdb:2.4.0
        ports:
        - 28015:28015

    container:
      image: crystallang/crystal:0.32.1

    steps:
    - uses: actions/checkout@v1

    - name: Add Debian (experimental) to APT sources
      run: echo "deb http://httpredir.debian.org/debian/ experimental main contrib non-free" > /etc/apt/sources.list

    - name: Apt Update
      run: apt-get update

    - name: Install Duktape and RocksDB from APT
      run: apt-get install duktape-dev librocksdb-dev -y

    - name: Install dependencies from shards
      run: shards install

    - name: Build main.cr
      run: crystal build src/main.cr

    - name: Run tests
      run: crystal spec

    - name: Check format
      run: crystal tool format --check
